version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    init: true


  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inception

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - backend

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception

  ftp_server:
    container_name: ftp_server
    build: ./requirements/bonus/ftp_server
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: always
    networks:
      - inception

  hugo:
    container_name: hugo
    build: ./requirements/bonus/hugo
    restart: always
    networks:
      - inception


volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/mbouthai/data/mysql
      type: none
      o: bind
      
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/mbouthai/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge