version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    expose:
      - 443
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    init: true

  wordpress:
    build:
      conext: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/mbouthai/data/mariadb
      type: none
      o: bind
      
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/mbouthai/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge