version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:${TAG}
    container_name: nginx
    restart: always
    env_file:
      - .env
    expose:
      - 443
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
    networks:
      - inception
    
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:${TAG}
    container_name: mariadb
    restart: always
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 10s
      timeout: 10s
      retries: 3

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:${TAG}
    container_name: wordpress
    restart: always
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - inception
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      start_period: 20s
      timeout: 10s
      retries: 5

  ftp_server:
      build:
        context: ./requirements/bonus/ftp_server
        dockerfile: Dockerfile
      image: ftp_server:${TAG}
      container_name: ftp_server
      restart: always
      env_file:
        - .env
      expose:
        - 21
      ports:
        - "21:21"
        - "40100-40200:40100-40200"
      volumes:
        - wordpress_volume:/var/www/wordpress
      networks:
        - inception
      depends_on:
        wordpress:
          condition: service_healthy

  redis:
      build:
        context: ./requirements/bonus/redis
        dockerfile: Dockerfile
      image: redis:${TAG}
      container_name: redis
      restart: always
      env_file:
        - .env
      expose:
        - 6379
      networks:
        - inception
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        start_period: 10s
        timeout: 10s
        retries: 3

  adminer:
      build:
        context: ./requirements/bonus/adminer
        dockerfile: Dockerfile
      image: adminer:${TAG}
      container_name: adminer
      restart: always
      env_file:
        - .env
      expose:
        - 9000
      networks:
        - inception
      healthcheck:
        test: netstat -an | grep 9000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
        start_period: 10s
        timeout: 10s
        retries: 5

  static_page:
      build:
        context: ./requirements/bonus/static_page
        dockerfile: Dockerfile
      image: static_page:${TAG}
      container_name: static_page
      restart: always
      env_file:
        - .env
      expose:
        - 3000
      ports:
        - "3000:3000"
      networks:
        - inception

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/mbouthai/data/mariadb
      type: none
      o: bind
      
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/mbouthai/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge