version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:${TAG}
    container_name: nginx
    restart: always
    env_file:
      - .env
    expose:
      - 443
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:${TAG}
    container_name: mariadb
    restart: always
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    init: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 20s

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:${TAG}
    container_name: wordpress
    restart: always
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception

  ftp_server:
    build:
      context: ./requirements/bonus/ftp_server
      dockerfile: Dockerfile
    image: ftp_server:${TAG}
    container_name: ftp_server
    restart: always
    env_file:
      - .env
    expose:
      - 21
    ports:
      - "21:21"
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/mbouthai/data/mariadb
      type: none
      o: bind
      
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/mbouthai/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge